apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: classlion
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: 172.30.4.83/msa/backend:classlion
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 8880
      imagePullSecrets:
        - name: harbor
