apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: classlion
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 8880
      targetPort: 8880
      nodePort: 31011
