apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: classlion
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: backend
          image: 172.30.4.83/msa/frontend:classlion
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: harbor
